name: Release Package

on:
  push:
    tags:
      - 'v*'
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Initialize Nitrogen bindings
      run: npm run nitrogen:init
      
    - name: Build package
      run: npm pack
      
    - name: Get package info
      id: package-info
      run: |
        PACKAGE_NAME=$(node -p "require('./package.json').name")
        PACKAGE_VERSION=$(node -p "require('./package.json').version")
        echo "name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
        echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
        echo "filename=${PACKAGE_NAME}-${PACKAGE_VERSION}.tgz" >> $GITHUB_OUTPUT
        
    - name: List files for debugging
      run: ls -la *.tgz
      
    - name: Create Release
      uses: softprops/action-gh-release@v2.0.4
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ steps.package-info.outputs.version }}
        body: |
          ## react-native-conceal-crypto v${{ steps.package-info.outputs.version }}
          
          ### Installation
          ```bash
          npm install ${{ steps.package-info.outputs.filename }}
          ```

        files: ${{ steps.package-info.outputs.filename }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
